version: '3'
services:
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment: 
      - DB_USERNAME=admin
      - DB_PASSWORD=testing
      - DB_DIALECT=mysql
      - DB_ADDRESS=mathapp_mysql:3306
      - DB_DATABASE=mathapp
      - PORT=8000
    container_name: mathapp_api
    ports:
      - "8000:8000"
    restart: always
    links:
      - mathapp_mysql
    volumes:
     - ./:/home/node/app

  mathapp_mysql:
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password_root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=mathapp
    container_name: mathapp_mysql