version: '3'
services:
  node:
    build: mathapp_api
    image: grymwulf/mathapp_api
    user: "node"
    working_dir: /home/node/app
    environment: 
      - DB_USERNAME=admin
      - DB_PASSWORD=testing
      - DB_DIALECT=mysql
      - DB_ADDRESS=mathapp_mysql:3306
      - DB_DATABASE=mathapp
      - PORT=8000
    container_name: mathapp_api
    ports:
      - "8000:8000"
    restart: always
    links:
      - mathapp_mysql
    volumes:
      - ./mathapp_api/docker_volume/data:/home/node/app/data
    command: npm start

  mathapp_mysql:
    build: mathapp_mysql
    image: grymwulf/mathapp_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password_root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=testing
      - MYSQL_DATABASE=mathapp
    container_name: mathapp_mysql